import fs from "node:fs";
import path from "node:path";
import { globSync } from "glob";
import matter from "gray-matter";

interface NavItem {
    title: string;
    slug?: string;
    description?: string;
    category?: string;
    order?: number;
    children?: NavItem[];
}

interface SearchEntry {
    title: string;
    description: string;
    slug: string;
    category: string;
}

const contentDir = path.resolve(import.meta.dirname, "../src/content");
const outputFile = path.resolve(import.meta.dirname, "../src/config/navigation.ts");

const files = globSync("**/*.mdx", { cwd: contentDir });

interface FlatItem {
    slug: string;
    segments: string[];
    title: string;
    description: string;
    category: string;
    order: number;
}

const flatItems: FlatItem[] = files.map((file) => {
    const fullPath = path.join(contentDir, file);
    const raw = fs.readFileSync(fullPath, "utf-8");
    const { data } = matter(raw);

    const slugPath = file
        .replace(/\.mdx$/, "")
        .replace(/\/index$/, "");

    return {
        slug: "/" + slugPath,
        segments: slugPath.split("/"),
        title: (data.title as string) ?? slugPath.split("/").pop()!.replace(/-/g, " "),
        description: (data.description as string) ?? "",
        category: (data.category as string) ?? slugPath.split("/")[0] ?? "",
        order: (data.order as number) ?? 99,
    };
});

flatItems.sort((a, b) => a.order - b.order);

const navItemsFiltered = flatItems.filter((item) => {
    if (item.category !== "components") return true;
    if (item.slug === "/components") return true;
    if (item.slug.startsWith("/components/sandbox-registry")) return true;
    return false;
});

function buildTree(items: FlatItem[], depth: number = 0, prefix: string = ""): NavItem[] {
    const groups = new Map<string, FlatItem[]>();

    for (const item of items) {
        if (item.segments.length === 0) continue;
        const key = item.segments[0]!;
        if (!groups.has(key)) groups.set(key, []);
        groups.get(key)!.push(item);
    }

    const result: NavItem[] = [];

    for (const [key, groupItems] of groups) {
        const indexItem = groupItems.find((i) => i.segments.length === 1);
        const childItems = groupItems
            .filter((i) => i.segments.length > 1)
            .map((i) => ({ ...i, segments: i.segments.slice(1) }));

        const children = buildTree(childItems, depth + 1, prefix ? `${prefix}/${key}` : key);

        if (children.length > 0) {
            result.push({
                title: indexItem?.title ?? key.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
                slug: indexItem?.slug,
                description: indexItem?.description,
                category: indexItem?.category,
                order: indexItem?.order ?? 99,
                children,
            });
        } else if (indexItem) {
            result.push({
                title: indexItem.title,
                slug: indexItem.slug,
                description: indexItem.description,
                category: indexItem.category,
                order: indexItem.order,
            });
        }
    }

    return result.sort((a, b) => (a.order ?? 99) - (b.order ?? 99));
}

const navItems = buildTree(navItemsFiltered);

const searchIndex: SearchEntry[] = navItemsFiltered.map((i) => ({
    title: i.title,
    description: i.description,
    slug: i.slug,
    category: i.category,
}));

const output = `// Auto-generated by scripts/generate-nav.ts — DO NOT EDIT
export interface NavItem {
    title: string;
    slug?: string;
    description?: string;
    category?: string;
    order?: number;
    children?: NavItem[];
}

export const navItems: NavItem[] = ${JSON.stringify(navItems, null, 2)};

export const searchIndex: Array<{
    title: string;
    description: string;
    slug: string;
    category: string;
}> = ${JSON.stringify(searchIndex, null, 2)};
`;

fs.writeFileSync(outputFile, output, "utf-8");
console.log(`Generated navigation with ${navItemsFiltered.length} pages.`);
