// Auto-generated by scripts/generate-nav.ts — DO NOT EDIT
export interface NavItem {
    title: string;
    slug?: string;
    description?: string;
    category?: string;
    order?: number;
    children?: NavItem[];
}

export const navItems: NavItem[] = [
  {
    "title": "Platform Overview",
    "slug": "/getting-started",
    "description": "Introduction to the MIBO intelligent financial assistant platform",
    "category": "getting-started",
    "order": 1,
    "children": [
      {
        "title": "Installation",
        "slug": "/getting-started/installation",
        "description": "How to set up and run the MIBO platform locally",
        "category": "getting-started",
        "order": 2
      },
      {
        "title": "Project Structure",
        "slug": "/getting-started/project-structure",
        "description": "Overview of the MIBO repository layout and file organization",
        "category": "getting-started",
        "order": 3
      }
    ]
  },
  {
    "title": "Architecture Overview",
    "slug": "/architecture",
    "description": "High-level architecture of the MIBO microservices platform",
    "category": "architecture",
    "order": 10,
    "children": [
      {
        "title": "Service Descriptions",
        "slug": "/architecture/services",
        "description": "Detailed overview of each MIBO microservice",
        "category": "architecture",
        "order": 11
      },
      {
        "title": "Inter-Service Communication",
        "slug": "/architecture/communication",
        "description": "How MIBO services communicate via NATS and SignalR",
        "category": "architecture",
        "order": 12
      }
    ]
  },
  {
    "title": "API Reference",
    "slug": "/api-reference",
    "description": "Complete REST API documentation for the MIBO platform",
    "category": "api-reference",
    "order": 20,
    "children": [
      {
        "title": "Identity",
        "order": 99,
        "children": [
          {
            "title": "Authentication",
            "slug": "/api-reference/identity/auth",
            "description": "Identity Service authentication endpoints - login, register, tokens",
            "category": "api-reference",
            "order": 21
          }
        ]
      },
      {
        "title": "Conversation",
        "order": 99,
        "children": [
          {
            "title": "Chat",
            "slug": "/api-reference/conversation/chat",
            "description": "Main chat endpoint for sending messages to the AI assistant",
            "category": "api-reference",
            "order": 22
          },
          {
            "title": "Streaming",
            "slug": "/api-reference/conversation/streaming",
            "description": "Server-Sent Events endpoint for streaming AI responses",
            "category": "api-reference",
            "order": 23
          },
          {
            "title": "Actions",
            "slug": "/api-reference/conversation/actions",
            "description": "Action execution endpoint for generative UI interactions",
            "category": "api-reference",
            "order": 24
          }
        ]
      },
      {
        "title": "Finance",
        "order": 99,
        "children": [
          {
            "title": "Accounts",
            "slug": "/api-reference/finance/accounts",
            "description": "Bank account management endpoints",
            "category": "api-reference",
            "order": 25
          },
          {
            "title": "Transactions",
            "slug": "/api-reference/finance/transactions",
            "description": "Transaction query and search endpoints",
            "category": "api-reference",
            "order": 26
          },
          {
            "title": "Expenses",
            "slug": "/api-reference/finance/expenses",
            "description": "Expense tracking and categorization endpoints",
            "category": "api-reference",
            "order": 27
          },
          {
            "title": "Budgets",
            "slug": "/api-reference/finance/budgets",
            "description": "Budget management endpoints",
            "category": "api-reference",
            "order": 28
          },
          {
            "title": "Summary",
            "slug": "/api-reference/finance/summary",
            "description": "Financial summary endpoints for user overviews",
            "category": "api-reference",
            "order": 29
          },
          {
            "title": "Analytics",
            "slug": "/api-reference/finance/analytics",
            "description": "Spending analytics and insights endpoints",
            "category": "api-reference",
            "order": 30
          }
        ]
      }
    ]
  },
  {
    "title": "Component Library",
    "slug": "/components",
    "description": "Overview of MIBO's reusable UI component library",
    "category": "components",
    "order": 40,
    "children": [
      {
        "title": "Button",
        "slug": "/components/button",
        "description": "Multi-variant button component with size and style options",
        "category": "components",
        "order": 41
      },
      {
        "title": "Card",
        "slug": "/components/card",
        "description": "Compound card component with header, title, content, and footer sections",
        "category": "components",
        "order": 42
      },
      {
        "title": "Input",
        "slug": "/components/input",
        "description": "Form input component with label, hint, and error states",
        "category": "components",
        "order": 43
      },
      {
        "title": "Select",
        "slug": "/components/select",
        "description": "Styled select dropdown with label, hint, and error support",
        "category": "components",
        "order": 44
      },
      {
        "title": "Textarea",
        "slug": "/components/textarea",
        "description": "Minimal textarea component with transparent background",
        "category": "components",
        "order": 45
      },
      {
        "title": "Badge",
        "slug": "/components/badge",
        "description": "Inline badge component with multiple visual variants",
        "category": "components",
        "order": 46
      },
      {
        "title": "Table",
        "slug": "/components/table",
        "description": "Compound table component with styled head, body, rows, and cells",
        "category": "components",
        "order": 47
      },
      {
        "title": "Spinner",
        "slug": "/components/spinner",
        "description": "Animated loading spinner component",
        "category": "components",
        "order": 48
      },
      {
        "title": "IconButton",
        "slug": "/components/icon-button",
        "description": "Square button component optimized for icon content",
        "category": "components",
        "order": 49
      }
    ]
  },
  {
    "title": "Chat System",
    "slug": "/chat-system",
    "description": "Overview of MIBO's AI-powered conversational interface",
    "category": "chat-system",
    "order": 50,
    "children": [
      {
        "title": "Conversation Flow",
        "slug": "/chat-system/conversation-flow",
        "description": "Detailed flow of a conversation from user input to AI response",
        "category": "chat-system",
        "order": 51
      },
      {
        "title": "Real-Time Features",
        "slug": "/chat-system/realtime",
        "description": "SignalR and SSE streaming in the MIBO chat system",
        "category": "chat-system",
        "order": 52
      }
    ]
  },
  {
    "title": "Deployment",
    "slug": "/deployment",
    "description": "Deployment architecture and infrastructure overview for the MIBO platform",
    "category": "deployment",
    "order": 60,
    "children": [
      {
        "title": "Docker",
        "slug": "/deployment/docker",
        "description": "Running MIBO with Docker Compose",
        "category": "deployment",
        "order": 61
      },
      {
        "title": "Kubernetes",
        "slug": "/deployment/kubernetes",
        "description": "Kubernetes deployment architecture and manifest structure",
        "category": "deployment",
        "order": 62
      },
      {
        "title": "Helm Charts",
        "slug": "/deployment/helm",
        "description": "Helm chart structure and configuration for MIBO services",
        "category": "deployment",
        "order": 63
      },
      {
        "title": "Infrastructure",
        "slug": "/deployment/infrastructure",
        "description": "Stateful infrastructure services - NATS, Redis, and PostgreSQL on Kubernetes",
        "category": "deployment",
        "order": 64
      },
      {
        "title": "Ingress & TLS",
        "slug": "/deployment/ingress",
        "description": "Traefik ingress controller with automatic Let's Encrypt TLS certificates",
        "category": "deployment",
        "order": 65
      },
      {
        "title": "Observability",
        "slug": "/deployment/observability",
        "description": "Monitoring, logging, and tracing with OpenTelemetry, Prometheus, Grafana, and Loki",
        "category": "deployment",
        "order": 66
      }
    ]
  }
];

export const searchIndex: Array<{
    title: string;
    description: string;
    slug: string;
    category: string;
}> = [
  {
    "title": "Platform Overview",
    "description": "Introduction to the MIBO intelligent financial assistant platform",
    "slug": "/getting-started",
    "category": "getting-started"
  },
  {
    "title": "Installation",
    "description": "How to set up and run the MIBO platform locally",
    "slug": "/getting-started/installation",
    "category": "getting-started"
  },
  {
    "title": "Project Structure",
    "description": "Overview of the MIBO repository layout and file organization",
    "slug": "/getting-started/project-structure",
    "category": "getting-started"
  },
  {
    "title": "Architecture Overview",
    "description": "High-level architecture of the MIBO microservices platform",
    "slug": "/architecture",
    "category": "architecture"
  },
  {
    "title": "Service Descriptions",
    "description": "Detailed overview of each MIBO microservice",
    "slug": "/architecture/services",
    "category": "architecture"
  },
  {
    "title": "Inter-Service Communication",
    "description": "How MIBO services communicate via NATS and SignalR",
    "slug": "/architecture/communication",
    "category": "architecture"
  },
  {
    "title": "API Reference",
    "description": "Complete REST API documentation for the MIBO platform",
    "slug": "/api-reference",
    "category": "api-reference"
  },
  {
    "title": "Authentication",
    "description": "Identity Service authentication endpoints - login, register, tokens",
    "slug": "/api-reference/identity/auth",
    "category": "api-reference"
  },
  {
    "title": "Chat",
    "description": "Main chat endpoint for sending messages to the AI assistant",
    "slug": "/api-reference/conversation/chat",
    "category": "api-reference"
  },
  {
    "title": "Streaming",
    "description": "Server-Sent Events endpoint for streaming AI responses",
    "slug": "/api-reference/conversation/streaming",
    "category": "api-reference"
  },
  {
    "title": "Actions",
    "description": "Action execution endpoint for generative UI interactions",
    "slug": "/api-reference/conversation/actions",
    "category": "api-reference"
  },
  {
    "title": "Accounts",
    "description": "Bank account management endpoints",
    "slug": "/api-reference/finance/accounts",
    "category": "api-reference"
  },
  {
    "title": "Transactions",
    "description": "Transaction query and search endpoints",
    "slug": "/api-reference/finance/transactions",
    "category": "api-reference"
  },
  {
    "title": "Expenses",
    "description": "Expense tracking and categorization endpoints",
    "slug": "/api-reference/finance/expenses",
    "category": "api-reference"
  },
  {
    "title": "Budgets",
    "description": "Budget management endpoints",
    "slug": "/api-reference/finance/budgets",
    "category": "api-reference"
  },
  {
    "title": "Summary",
    "description": "Financial summary endpoints for user overviews",
    "slug": "/api-reference/finance/summary",
    "category": "api-reference"
  },
  {
    "title": "Analytics",
    "description": "Spending analytics and insights endpoints",
    "slug": "/api-reference/finance/analytics",
    "category": "api-reference"
  },
  {
    "title": "Component Library",
    "description": "Overview of MIBO's reusable UI component library",
    "slug": "/components",
    "category": "components"
  },
  {
    "title": "Button",
    "description": "Multi-variant button component with size and style options",
    "slug": "/components/button",
    "category": "components"
  },
  {
    "title": "Card",
    "description": "Compound card component with header, title, content, and footer sections",
    "slug": "/components/card",
    "category": "components"
  },
  {
    "title": "Input",
    "description": "Form input component with label, hint, and error states",
    "slug": "/components/input",
    "category": "components"
  },
  {
    "title": "Select",
    "description": "Styled select dropdown with label, hint, and error support",
    "slug": "/components/select",
    "category": "components"
  },
  {
    "title": "Textarea",
    "description": "Minimal textarea component with transparent background",
    "slug": "/components/textarea",
    "category": "components"
  },
  {
    "title": "Badge",
    "description": "Inline badge component with multiple visual variants",
    "slug": "/components/badge",
    "category": "components"
  },
  {
    "title": "Table",
    "description": "Compound table component with styled head, body, rows, and cells",
    "slug": "/components/table",
    "category": "components"
  },
  {
    "title": "Spinner",
    "description": "Animated loading spinner component",
    "slug": "/components/spinner",
    "category": "components"
  },
  {
    "title": "IconButton",
    "description": "Square button component optimized for icon content",
    "slug": "/components/icon-button",
    "category": "components"
  },
  {
    "title": "Chat System",
    "description": "Overview of MIBO's AI-powered conversational interface",
    "slug": "/chat-system",
    "category": "chat-system"
  },
  {
    "title": "Conversation Flow",
    "description": "Detailed flow of a conversation from user input to AI response",
    "slug": "/chat-system/conversation-flow",
    "category": "chat-system"
  },
  {
    "title": "Real-Time Features",
    "description": "SignalR and SSE streaming in the MIBO chat system",
    "slug": "/chat-system/realtime",
    "category": "chat-system"
  },
  {
    "title": "Deployment",
    "description": "Deployment architecture and infrastructure overview for the MIBO platform",
    "slug": "/deployment",
    "category": "deployment"
  },
  {
    "title": "Docker",
    "description": "Running MIBO with Docker Compose",
    "slug": "/deployment/docker",
    "category": "deployment"
  },
  {
    "title": "Kubernetes",
    "description": "Kubernetes deployment architecture and manifest structure",
    "slug": "/deployment/kubernetes",
    "category": "deployment"
  },
  {
    "title": "Helm Charts",
    "description": "Helm chart structure and configuration for MIBO services",
    "slug": "/deployment/helm",
    "category": "deployment"
  },
  {
    "title": "Infrastructure",
    "description": "Stateful infrastructure services - NATS, Redis, and PostgreSQL on Kubernetes",
    "slug": "/deployment/infrastructure",
    "category": "deployment"
  },
  {
    "title": "Ingress & TLS",
    "description": "Traefik ingress controller with automatic Let's Encrypt TLS certificates",
    "slug": "/deployment/ingress",
    "category": "deployment"
  },
  {
    "title": "Observability",
    "description": "Monitoring, logging, and tracing with OpenTelemetry, Prometheus, Grafana, and Loki",
    "slug": "/deployment/observability",
    "category": "deployment"
  }
];
