// Auto-generated by scripts/generate-nav.ts — DO NOT EDIT
export interface NavItem {
    title: string;
    slug?: string;
    description?: string;
    category?: string;
    order?: number;
    children?: NavItem[];
}

export const navItems: NavItem[] = [
  {
    "title": "Platform Overview",
    "slug": "/getting-started",
    "description": "Introduction to the MIBO intelligent financial assistant platform",
    "category": "getting-started",
    "order": 1,
    "children": [
      {
        "title": "Installation",
        "slug": "/getting-started/installation",
        "description": "How to set up and run the MIBO platform locally",
        "category": "getting-started",
        "order": 2
      },
      {
        "title": "Project Structure",
        "slug": "/getting-started/project-structure",
        "description": "Overview of the MIBO repository layout and file organization",
        "category": "getting-started",
        "order": 3
      }
    ]
  },
  {
    "title": "Architecture Overview",
    "slug": "/architecture",
    "description": "High-level architecture of the MIBO microservices platform",
    "category": "architecture",
    "order": 10,
    "children": [
      {
        "title": "Service Descriptions",
        "slug": "/architecture/services",
        "description": "Detailed overview of each MIBO microservice",
        "category": "architecture",
        "order": 11
      },
      {
        "title": "Inter-Service Communication",
        "slug": "/architecture/communication",
        "description": "How MIBO services communicate via NATS and SignalR",
        "category": "architecture",
        "order": 12
      }
    ]
  },
  {
    "title": "API Reference",
    "slug": "/api-reference",
    "description": "Complete REST API documentation for the MIBO platform",
    "category": "api-reference",
    "order": 20,
    "children": [
      {
        "title": "Identity",
        "order": 99,
        "children": [
          {
            "title": "Authentication",
            "slug": "/api-reference/identity/auth",
            "description": "Identity Service authentication endpoints - login, register, tokens",
            "category": "api-reference",
            "order": 21
          }
        ]
      },
      {
        "title": "Conversation",
        "order": 99,
        "children": [
          {
            "title": "Chat",
            "slug": "/api-reference/conversation/chat",
            "description": "Main chat endpoint for sending messages to the AI assistant",
            "category": "api-reference",
            "order": 22
          },
          {
            "title": "Streaming",
            "slug": "/api-reference/conversation/streaming",
            "description": "Server-Sent Events endpoint for streaming AI responses",
            "category": "api-reference",
            "order": 23
          },
          {
            "title": "Actions",
            "slug": "/api-reference/conversation/actions",
            "description": "Action execution endpoint for generative UI interactions",
            "category": "api-reference",
            "order": 24
          }
        ]
      },
      {
        "title": "Finance",
        "order": 99,
        "children": [
          {
            "title": "Accounts",
            "slug": "/api-reference/finance/accounts",
            "description": "Bank account management endpoints",
            "category": "api-reference",
            "order": 25
          },
          {
            "title": "Transactions",
            "slug": "/api-reference/finance/transactions",
            "description": "Transaction query and search endpoints",
            "category": "api-reference",
            "order": 26
          },
          {
            "title": "Expenses",
            "slug": "/api-reference/finance/expenses",
            "description": "Expense tracking and categorization endpoints",
            "category": "api-reference",
            "order": 27
          },
          {
            "title": "Budgets",
            "slug": "/api-reference/finance/budgets",
            "description": "Budget management endpoints",
            "category": "api-reference",
            "order": 28
          },
          {
            "title": "Summary",
            "slug": "/api-reference/finance/summary",
            "description": "Financial summary endpoints for user overviews",
            "category": "api-reference",
            "order": 29
          },
          {
            "title": "Analytics",
            "slug": "/api-reference/finance/analytics",
            "description": "Spending analytics and insights endpoints",
            "category": "api-reference",
            "order": 30
          }
        ]
      }
    ]
  },
  {
    "title": "Component Library",
    "slug": "/components",
    "description": "Documentation for the sandbox UI registry used by dynamic client rendering",
    "category": "components",
    "order": 40,
    "children": [
      {
        "title": "Sandbox Registry Components",
        "slug": "/components/sandbox-registry",
        "description": "Complete documentation for all dynamic UI components used by client sandbox runtime",
        "category": "components",
        "order": 70,
        "children": [
          {
            "title": "ActionPanel",
            "slug": "/components/sandbox-registry/action-panel",
            "description": "Action orchestration panel with payload templates and variant buttons",
            "category": "components",
            "order": 71
          },
          {
            "title": "BarChartCard",
            "slug": "/components/sandbox-registry/bar-chart-card",
            "description": "SVG bar chart with grouped, stacked and horizontal modes",
            "category": "components",
            "order": 72
          },
          {
            "title": "Carousel",
            "slug": "/components/sandbox-registry/carousel",
            "description": "Generic registry-based horizontal list renderer",
            "category": "components",
            "order": 73
          },
          {
            "title": "CartSummaryCard",
            "slug": "/components/sandbox-registry/cart-summary-card",
            "description": "Checkout summary card with product rows and totals",
            "category": "components",
            "order": 74
          },
          {
            "title": "CategoryChips",
            "slug": "/components/sandbox-registry/category-chips",
            "description": "Interactive category selector for filtering flows",
            "category": "components",
            "order": 75
          },
          {
            "title": "EmailComposer",
            "slug": "/components/sandbox-registry/email-composer",
            "description": "Gmail-oriented email draft composer with editable recipients, subject and body",
            "category": "components",
            "order": 76
          },
          {
            "title": "DataTableCard",
            "slug": "/components/sandbox-registry/data-table-card",
            "description": "Configurable table with search, sorting, and actions",
            "category": "components",
            "order": 76
          },
          {
            "title": "FormCard",
            "slug": "/components/sandbox-registry/form-card",
            "description": "Schema-driven dynamic form with submit and reset actions",
            "category": "components",
            "order": 77
          },
          {
            "title": "JsonViewerCard",
            "slug": "/components/sandbox-registry/json-viewer-card",
            "description": "JSON inspector with collapsible raw output",
            "category": "components",
            "order": 78
          },
          {
            "title": "KpiCard",
            "slug": "/components/sandbox-registry/kpi-card",
            "description": "Single metric card for dashboard KPIs",
            "category": "components",
            "order": 79
          },
          {
            "title": "LineChartCard",
            "slug": "/components/sandbox-registry/line-chart-card",
            "description": "Interactive line chart with optional area and legend",
            "category": "components",
            "order": 80
          },
          {
            "title": "Markdown",
            "slug": "/components/sandbox-registry/markdown",
            "description": "Markdown renderer with GFM and code highlighting",
            "category": "components",
            "order": 81
          },
          {
            "title": "PageTitle",
            "slug": "/components/sandbox-registry/page-title",
            "description": "Title and subtitle block with runtime binding",
            "category": "components",
            "order": 82
          },
          {
            "title": "Pagination",
            "slug": "/components/sandbox-registry/pagination",
            "description": "Prev/next pager with computed page state",
            "category": "components",
            "order": 83
          },
          {
            "title": "PieChartCard",
            "slug": "/components/sandbox-registry/pie-chart-card",
            "description": "Donut-style pie chart with legend and hover focus",
            "category": "components",
            "order": 84
          },
          {
            "title": "ProductCarouselCard",
            "slug": "/components/sandbox-registry/product-carousel-card",
            "description": "Product rail with open and secondary actions",
            "category": "components",
            "order": 85
          },
          {
            "title": "ProductDetailCard",
            "slug": "/components/sandbox-registry/product-detail-card",
            "description": "Detailed product card with quantity and cart action",
            "category": "components",
            "order": 86
          },
          {
            "title": "SearchBar",
            "slug": "/components/sandbox-registry/search-bar",
            "description": "Search input with Enter and button submit actions",
            "category": "components",
            "order": 87
          },
          {
            "title": "SortDropdown",
            "slug": "/components/sandbox-registry/sort-dropdown",
            "description": "Sort selector with customizable option payloads",
            "category": "components",
            "order": 88
          },
          {
            "title": "SummaryPanel",
            "slug": "/components/sandbox-registry/summary-panel",
            "description": "Multi-KPI panel with trends and sparkline mini charts",
            "category": "components",
            "order": 89
          },
          {
            "title": "TimelineCard",
            "slug": "/components/sandbox-registry/timeline-card",
            "description": "Event timeline list with clickable items",
            "category": "components",
            "order": 90
          }
        ]
      }
    ]
  },
  {
    "title": "Chat System",
    "slug": "/chat-system",
    "description": "Overview of MIBO's AI-powered conversational interface",
    "category": "chat-system",
    "order": 50,
    "children": [
      {
        "title": "Conversation Flow",
        "slug": "/chat-system/conversation-flow",
        "description": "Detailed flow of a conversation from user input to AI response",
        "category": "chat-system",
        "order": 51
      },
      {
        "title": "Real-Time Features",
        "slug": "/chat-system/realtime",
        "description": "SignalR and SSE streaming in the MIBO chat system",
        "category": "chat-system",
        "order": 52
      }
    ]
  },
  {
    "title": "Deployment",
    "slug": "/deployment",
    "description": "Deployment architecture and infrastructure overview for the MIBO platform",
    "category": "deployment",
    "order": 60,
    "children": [
      {
        "title": "Docker",
        "slug": "/deployment/docker",
        "description": "Running MIBO with Docker Compose",
        "category": "deployment",
        "order": 61
      },
      {
        "title": "Kubernetes",
        "slug": "/deployment/kubernetes",
        "description": "Kubernetes deployment architecture and manifest structure",
        "category": "deployment",
        "order": 62
      },
      {
        "title": "Helm Charts",
        "slug": "/deployment/helm",
        "description": "Helm chart structure and configuration for MIBO services",
        "category": "deployment",
        "order": 63
      },
      {
        "title": "Infrastructure",
        "slug": "/deployment/infrastructure",
        "description": "Stateful infrastructure services - NATS, Redis, and PostgreSQL on Kubernetes",
        "category": "deployment",
        "order": 64
      },
      {
        "title": "Ingress & TLS",
        "slug": "/deployment/ingress",
        "description": "Traefik ingress controller with automatic Let's Encrypt TLS certificates",
        "category": "deployment",
        "order": 65
      },
      {
        "title": "Observability",
        "slug": "/deployment/observability",
        "description": "Monitoring, logging, and tracing with OpenTelemetry, Prometheus, Grafana, and Loki",
        "category": "deployment",
        "order": 66
      }
    ]
  }
];

export const searchIndex: Array<{
    title: string;
    description: string;
    slug: string;
    category: string;
}> = [
  {
    "title": "Platform Overview",
    "description": "Introduction to the MIBO intelligent financial assistant platform",
    "slug": "/getting-started",
    "category": "getting-started"
  },
  {
    "title": "Installation",
    "description": "How to set up and run the MIBO platform locally",
    "slug": "/getting-started/installation",
    "category": "getting-started"
  },
  {
    "title": "Project Structure",
    "description": "Overview of the MIBO repository layout and file organization",
    "slug": "/getting-started/project-structure",
    "category": "getting-started"
  },
  {
    "title": "Architecture Overview",
    "description": "High-level architecture of the MIBO microservices platform",
    "slug": "/architecture",
    "category": "architecture"
  },
  {
    "title": "Service Descriptions",
    "description": "Detailed overview of each MIBO microservice",
    "slug": "/architecture/services",
    "category": "architecture"
  },
  {
    "title": "Inter-Service Communication",
    "description": "How MIBO services communicate via NATS and SignalR",
    "slug": "/architecture/communication",
    "category": "architecture"
  },
  {
    "title": "API Reference",
    "description": "Complete REST API documentation for the MIBO platform",
    "slug": "/api-reference",
    "category": "api-reference"
  },
  {
    "title": "Authentication",
    "description": "Identity Service authentication endpoints - login, register, tokens",
    "slug": "/api-reference/identity/auth",
    "category": "api-reference"
  },
  {
    "title": "Chat",
    "description": "Main chat endpoint for sending messages to the AI assistant",
    "slug": "/api-reference/conversation/chat",
    "category": "api-reference"
  },
  {
    "title": "Streaming",
    "description": "Server-Sent Events endpoint for streaming AI responses",
    "slug": "/api-reference/conversation/streaming",
    "category": "api-reference"
  },
  {
    "title": "Actions",
    "description": "Action execution endpoint for generative UI interactions",
    "slug": "/api-reference/conversation/actions",
    "category": "api-reference"
  },
  {
    "title": "Accounts",
    "description": "Bank account management endpoints",
    "slug": "/api-reference/finance/accounts",
    "category": "api-reference"
  },
  {
    "title": "Transactions",
    "description": "Transaction query and search endpoints",
    "slug": "/api-reference/finance/transactions",
    "category": "api-reference"
  },
  {
    "title": "Expenses",
    "description": "Expense tracking and categorization endpoints",
    "slug": "/api-reference/finance/expenses",
    "category": "api-reference"
  },
  {
    "title": "Budgets",
    "description": "Budget management endpoints",
    "slug": "/api-reference/finance/budgets",
    "category": "api-reference"
  },
  {
    "title": "Summary",
    "description": "Financial summary endpoints for user overviews",
    "slug": "/api-reference/finance/summary",
    "category": "api-reference"
  },
  {
    "title": "Analytics",
    "description": "Spending analytics and insights endpoints",
    "slug": "/api-reference/finance/analytics",
    "category": "api-reference"
  },
  {
    "title": "Component Library",
    "description": "Documentation for the sandbox UI registry used by dynamic client rendering",
    "slug": "/components",
    "category": "components"
  },
  {
    "title": "Chat System",
    "description": "Overview of MIBO's AI-powered conversational interface",
    "slug": "/chat-system",
    "category": "chat-system"
  },
  {
    "title": "Conversation Flow",
    "description": "Detailed flow of a conversation from user input to AI response",
    "slug": "/chat-system/conversation-flow",
    "category": "chat-system"
  },
  {
    "title": "Real-Time Features",
    "description": "SignalR and SSE streaming in the MIBO chat system",
    "slug": "/chat-system/realtime",
    "category": "chat-system"
  },
  {
    "title": "Deployment",
    "description": "Deployment architecture and infrastructure overview for the MIBO platform",
    "slug": "/deployment",
    "category": "deployment"
  },
  {
    "title": "Docker",
    "description": "Running MIBO with Docker Compose",
    "slug": "/deployment/docker",
    "category": "deployment"
  },
  {
    "title": "Kubernetes",
    "description": "Kubernetes deployment architecture and manifest structure",
    "slug": "/deployment/kubernetes",
    "category": "deployment"
  },
  {
    "title": "Helm Charts",
    "description": "Helm chart structure and configuration for MIBO services",
    "slug": "/deployment/helm",
    "category": "deployment"
  },
  {
    "title": "Infrastructure",
    "description": "Stateful infrastructure services - NATS, Redis, and PostgreSQL on Kubernetes",
    "slug": "/deployment/infrastructure",
    "category": "deployment"
  },
  {
    "title": "Ingress & TLS",
    "description": "Traefik ingress controller with automatic Let's Encrypt TLS certificates",
    "slug": "/deployment/ingress",
    "category": "deployment"
  },
  {
    "title": "Observability",
    "description": "Monitoring, logging, and tracing with OpenTelemetry, Prometheus, Grafana, and Loki",
    "slug": "/deployment/observability",
    "category": "deployment"
  },
  {
    "title": "Sandbox Registry Components",
    "description": "Complete documentation for all dynamic UI components used by client sandbox runtime",
    "slug": "/components/sandbox-registry",
    "category": "components"
  },
  {
    "title": "ActionPanel",
    "description": "Action orchestration panel with payload templates and variant buttons",
    "slug": "/components/sandbox-registry/action-panel",
    "category": "components"
  },
  {
    "title": "BarChartCard",
    "description": "SVG bar chart with grouped, stacked and horizontal modes",
    "slug": "/components/sandbox-registry/bar-chart-card",
    "category": "components"
  },
  {
    "title": "Carousel",
    "description": "Generic registry-based horizontal list renderer",
    "slug": "/components/sandbox-registry/carousel",
    "category": "components"
  },
  {
    "title": "CartSummaryCard",
    "description": "Checkout summary card with product rows and totals",
    "slug": "/components/sandbox-registry/cart-summary-card",
    "category": "components"
  },
  {
    "title": "CategoryChips",
    "description": "Interactive category selector for filtering flows",
    "slug": "/components/sandbox-registry/category-chips",
    "category": "components"
  },
  {
    "title": "EmailComposer",
    "description": "Gmail-oriented email draft composer with editable recipients, subject and body",
    "slug": "/components/sandbox-registry/email-composer",
    "category": "components"
  },
  {
    "title": "DataTableCard",
    "description": "Configurable table with search, sorting, and actions",
    "slug": "/components/sandbox-registry/data-table-card",
    "category": "components"
  },
  {
    "title": "FormCard",
    "description": "Schema-driven dynamic form with submit and reset actions",
    "slug": "/components/sandbox-registry/form-card",
    "category": "components"
  },
  {
    "title": "JsonViewerCard",
    "description": "JSON inspector with collapsible raw output",
    "slug": "/components/sandbox-registry/json-viewer-card",
    "category": "components"
  },
  {
    "title": "KpiCard",
    "description": "Single metric card for dashboard KPIs",
    "slug": "/components/sandbox-registry/kpi-card",
    "category": "components"
  },
  {
    "title": "LineChartCard",
    "description": "Interactive line chart with optional area and legend",
    "slug": "/components/sandbox-registry/line-chart-card",
    "category": "components"
  },
  {
    "title": "Markdown",
    "description": "Markdown renderer with GFM and code highlighting",
    "slug": "/components/sandbox-registry/markdown",
    "category": "components"
  },
  {
    "title": "PageTitle",
    "description": "Title and subtitle block with runtime binding",
    "slug": "/components/sandbox-registry/page-title",
    "category": "components"
  },
  {
    "title": "Pagination",
    "description": "Prev/next pager with computed page state",
    "slug": "/components/sandbox-registry/pagination",
    "category": "components"
  },
  {
    "title": "PieChartCard",
    "description": "Donut-style pie chart with legend and hover focus",
    "slug": "/components/sandbox-registry/pie-chart-card",
    "category": "components"
  },
  {
    "title": "ProductCarouselCard",
    "description": "Product rail with open and secondary actions",
    "slug": "/components/sandbox-registry/product-carousel-card",
    "category": "components"
  },
  {
    "title": "ProductDetailCard",
    "description": "Detailed product card with quantity and cart action",
    "slug": "/components/sandbox-registry/product-detail-card",
    "category": "components"
  },
  {
    "title": "SearchBar",
    "description": "Search input with Enter and button submit actions",
    "slug": "/components/sandbox-registry/search-bar",
    "category": "components"
  },
  {
    "title": "SortDropdown",
    "description": "Sort selector with customizable option payloads",
    "slug": "/components/sandbox-registry/sort-dropdown",
    "category": "components"
  },
  {
    "title": "SummaryPanel",
    "description": "Multi-KPI panel with trends and sparkline mini charts",
    "slug": "/components/sandbox-registry/summary-panel",
    "category": "components"
  },
  {
    "title": "TimelineCard",
    "description": "Event timeline list with clickable items",
    "slug": "/components/sandbox-registry/timeline-card",
    "category": "components"
  }
];
