// Auto-generated by scripts/generate-nav.ts — DO NOT EDIT
export interface NavItem {
    title: string;
    slug?: string;
    description?: string;
    category?: string;
    order?: number;
    children?: NavItem[];
}

export const navItems: NavItem[] = [
  {
    "title": "Platform Overview",
    "slug": "/getting-started",
    "description": "Current product, platform, and repository overview for MIBO",
    "category": "getting-started",
    "order": 1,
    "children": [
      {
        "title": "Installation",
        "slug": "/getting-started/installation",
        "description": "Recommended ways to run the MIBO platform locally and what each mode starts",
        "category": "getting-started",
        "order": 2
      },
      {
        "title": "Project Structure",
        "slug": "/getting-started/project-structure",
        "description": "Repository layout and how the codebase is partitioned by services, apps, infrastructure, and tests",
        "category": "getting-started",
        "order": 3
      },
      {
        "title": "Platform Snapshot",
        "slug": "/getting-started/current-state",
        "description": "Active platform summary for the current MIBO repository",
        "category": "getting-started",
        "order": 4
      }
    ]
  },
  {
    "title": "Architecture Overview",
    "slug": "/architecture",
    "description": "Current runtime architecture for the MIBO platform",
    "category": "architecture",
    "order": 10,
    "children": [
      {
        "title": "Services",
        "slug": "/architecture/services",
        "description": "Service catalog for the applications and shared runtime libraries in MIBO",
        "category": "architecture",
        "order": 11
      },
      {
        "title": "Communication",
        "slug": "/architecture/communication",
        "description": "Active request, streaming, identity propagation, and retry flows used by MIBO today",
        "category": "architecture",
        "order": 12
      },
      {
        "title": "Data Layer",
        "slug": "/architecture/data-layer",
        "description": "Persistence ownership across PostgreSQL, MongoDB, Redis, and RabbitMQ",
        "category": "architecture",
        "order": 13
      },
      {
        "title": "Frontend Apps",
        "slug": "/architecture/frontend-apps",
        "description": "The three frontend applications and the client-side generative UI runtime",
        "category": "architecture",
        "order": 14
      },
      {
        "title": "External Integrations",
        "slug": "/architecture/external-integrations",
        "description": "Runtime-facing third-party and adjacent external services used by the current MIBO platform",
        "category": "architecture",
        "order": 15
      }
    ]
  },
  {
    "title": "API Reference",
    "slug": "/api-reference",
    "description": "Public HTTP contracts and action runtime contracts used by the current MIBO platform",
    "category": "api-reference",
    "order": 20,
    "children": [
      {
        "title": "API Gateway",
        "slug": "/api-reference/gateway",
        "description": "Ocelot routes, authentication behavior, and claim propagation in MIBO.ApiGateway",
        "category": "api-reference",
        "order": 21
      },
      {
        "title": "Identity",
        "order": 99,
        "children": [
          {
            "title": "Identity & Auth",
            "slug": "/api-reference/identity/auth",
            "description": "Current IdentityService endpoints for login, registration, refresh, user info, finance connection state, and Spotify OAuth",
            "category": "api-reference",
            "order": 22
          }
        ]
      },
      {
        "title": "Conversation",
        "order": 99,
        "children": [
          {
            "title": "Chat",
            "slug": "/api-reference/conversation/chat",
            "description": "Live chat endpoint exposed by ConversationService through the gateway",
            "category": "api-reference",
            "order": 23
          },
          {
            "title": "Streaming",
            "slug": "/api-reference/conversation/streaming",
            "description": "SSE event format between ConversationService, LangChainService, and the React client",
            "category": "api-reference",
            "order": 24
          },
          {
            "title": "Conversation Management",
            "slug": "/api-reference/conversation/actions",
            "description": "CRUD contracts for conversations and their stored message history",
            "category": "api-reference",
            "order": 25
          }
        ]
      },
      {
        "title": "Action Service",
        "order": 99,
        "children": [
          {
            "title": "Action Service Runtime",
            "slug": "/api-reference/action-service/runtime",
            "description": "Public query and execute contracts plus the supported handler catalog in MIBO.ActionService",
            "category": "api-reference",
            "order": 26
          },
          {
            "title": "Integration Status",
            "slug": "/api-reference/action-service/status",
            "description": "Monitoring summary contract exposed by ActionService and consumed by the status frontend",
            "category": "api-reference",
            "order": 27
          }
        ]
      },
      {
        "title": "Finance",
        "order": 99,
        "children": [
          {
            "title": "Finance Accounts",
            "slug": "/api-reference/finance/accounts",
            "description": "Finance account handlers exposed through Action Service",
            "category": "api-reference",
            "order": 28
          },
          {
            "title": "Finance Transactions",
            "slug": "/api-reference/finance/transactions",
            "description": "Finance transaction list and search handlers exposed through Action Service",
            "category": "api-reference",
            "order": 29
          },
          {
            "title": "Finance Expenses",
            "slug": "/api-reference/finance/expenses",
            "description": "Expense list and expense category handlers exposed through Action Service",
            "category": "api-reference",
            "order": 30
          },
          {
            "title": "Finance Budgets",
            "slug": "/api-reference/finance/budgets",
            "description": "Budget handlers exposed through Action Service",
            "category": "api-reference",
            "order": 31
          },
          {
            "title": "Finance Summary",
            "slug": "/api-reference/finance/summary",
            "description": "Summary handlers used by the agent and generative UI",
            "category": "api-reference",
            "order": 32
          },
          {
            "title": "Finance Analytics",
            "slug": "/api-reference/finance/analytics",
            "description": "Expense and transaction analytics handlers exposed through Action Service",
            "category": "api-reference",
            "order": 33
          }
        ]
      }
    ]
  },
  {
    "title": "Component Library",
    "slug": "/components",
    "description": "Documentation for the sandbox UI registry used by the client-side generative UI runtime",
    "category": "components",
    "order": 40,
    "children": [
      {
        "title": "Sandbox Registry Components",
        "slug": "/components/sandbox-registry",
        "description": "Runtime component catalog for the generative UI registry used by the MIBO client",
        "category": "components",
        "order": 70,
        "children": [
          {
            "title": "ActionPanel",
            "slug": "/components/sandbox-registry/action-panel",
            "description": "Action orchestration panel with payload templates and variant buttons",
            "category": "components",
            "order": 71
          },
          {
            "title": "BarChartCard",
            "slug": "/components/sandbox-registry/bar-chart-card",
            "description": "SVG bar chart with grouped, stacked and horizontal modes",
            "category": "components",
            "order": 72
          },
          {
            "title": "Carousel",
            "slug": "/components/sandbox-registry/carousel",
            "description": "Generic registry-based horizontal list renderer",
            "category": "components",
            "order": 73
          },
          {
            "title": "CartSummaryCard",
            "slug": "/components/sandbox-registry/cart-summary-card",
            "description": "Checkout summary card with product rows and totals",
            "category": "components",
            "order": 74
          },
          {
            "title": "CategoryChips",
            "slug": "/components/sandbox-registry/category-chips",
            "description": "Interactive category selector for filtering flows",
            "category": "components",
            "order": 75
          },
          {
            "title": "EmailComposer",
            "slug": "/components/sandbox-registry/email-composer",
            "description": "Gmail-oriented email draft composer with editable recipients, subject and body",
            "category": "components",
            "order": 76
          },
          {
            "title": "DataTableCard",
            "slug": "/components/sandbox-registry/data-table-card",
            "description": "Configurable table with search, sorting, and actions",
            "category": "components",
            "order": 76
          },
          {
            "title": "FormCard",
            "slug": "/components/sandbox-registry/form-card",
            "description": "Schema-driven dynamic form with submit and reset actions",
            "category": "components",
            "order": 77
          },
          {
            "title": "JsonViewerCard",
            "slug": "/components/sandbox-registry/json-viewer-card",
            "description": "JSON inspector with collapsible raw output",
            "category": "components",
            "order": 78
          },
          {
            "title": "KpiCard",
            "slug": "/components/sandbox-registry/kpi-card",
            "description": "Single metric card for dashboard KPIs",
            "category": "components",
            "order": 79
          },
          {
            "title": "LineChartCard",
            "slug": "/components/sandbox-registry/line-chart-card",
            "description": "Interactive line chart with optional area and legend",
            "category": "components",
            "order": 80
          },
          {
            "title": "Markdown",
            "slug": "/components/sandbox-registry/markdown",
            "description": "Markdown renderer with GFM and code highlighting",
            "category": "components",
            "order": 81
          },
          {
            "title": "PageTitle",
            "slug": "/components/sandbox-registry/page-title",
            "description": "Title and subtitle block with runtime binding",
            "category": "components",
            "order": 82
          },
          {
            "title": "Pagination",
            "slug": "/components/sandbox-registry/pagination",
            "description": "Prev/next pager with computed page state",
            "category": "components",
            "order": 83
          },
          {
            "title": "PieChartCard",
            "slug": "/components/sandbox-registry/pie-chart-card",
            "description": "Donut-style pie chart with legend and hover focus",
            "category": "components",
            "order": 84
          },
          {
            "title": "ProductCarouselCard",
            "slug": "/components/sandbox-registry/product-carousel-card",
            "description": "Product rail with open and secondary actions",
            "category": "components",
            "order": 85
          },
          {
            "title": "ProductDetailCard",
            "slug": "/components/sandbox-registry/product-detail-card",
            "description": "Detailed product card with quantity and cart action",
            "category": "components",
            "order": 86
          },
          {
            "title": "SearchBar",
            "slug": "/components/sandbox-registry/search-bar",
            "description": "Search input with Enter and button submit actions",
            "category": "components",
            "order": 87
          },
          {
            "title": "SortDropdown",
            "slug": "/components/sandbox-registry/sort-dropdown",
            "description": "Sort selector with customizable option payloads",
            "category": "components",
            "order": 88
          },
          {
            "title": "SummaryPanel",
            "slug": "/components/sandbox-registry/summary-panel",
            "description": "Multi-KPI panel with trends and sparkline mini charts",
            "category": "components",
            "order": 89
          },
          {
            "title": "TimelineCard",
            "slug": "/components/sandbox-registry/timeline-card",
            "description": "Event timeline list with clickable items",
            "category": "components",
            "order": 90
          },
          {
            "title": "PomodoroTimer",
            "slug": "/components/sandbox-registry/pomodoro-timer",
            "description": "Runtime Pomodoro timer component available in the client sandbox registry",
            "category": "components",
            "order": 91
          },
          {
            "title": "SpotifyPlayer",
            "slug": "/components/sandbox-registry/spotify-player",
            "description": "Runtime Spotify now-playing card available in the client sandbox registry",
            "category": "components",
            "order": 92
          },
          {
            "title": "SpotifyTrackList",
            "slug": "/components/sandbox-registry/spotify-track-list",
            "description": "Runtime Spotify track-list component available in the client sandbox registry",
            "category": "components",
            "order": 93
          }
        ]
      }
    ]
  },
  {
    "title": "Chat & AI Overview",
    "slug": "/chat-system",
    "description": "End-to-end architecture for MIBO's conversational runtime, AI agent pipeline, and structured UI responses",
    "category": "chat-system",
    "order": 50,
    "children": [
      {
        "title": "Conversation Flow",
        "slug": "/chat-system/conversation-flow",
        "description": "Detailed lifecycle from browser prompt to persisted assistant payload and client-side generative UI",
        "category": "chat-system",
        "order": 51
      },
      {
        "title": "AI Agent Runtime",
        "slug": "/chat-system/ai-agent-runtime",
        "description": "Detailed architecture of MIBO.LangChainService, including graph execution, prompts, tool orchestration, memory, and output shaping",
        "category": "chat-system",
        "order": 52
      },
      {
        "title": "Conversation Service Runtime",
        "slug": "/chat-system/conversation-service-runtime",
        "description": "Detailed architecture of MIBO.ConversationService, including CRUD, SSE relay, Mongo persistence, ownership, and monitoring",
        "category": "chat-system",
        "order": 53
      },
      {
        "title": "Streaming & Live Runtime",
        "slug": "/chat-system/realtime",
        "description": "SSE protocol, event semantics, and structured response handling across ConversationService, LangChainService, and the React client",
        "category": "chat-system",
        "order": 54
      }
    ]
  },
  {
    "title": "Deployment",
    "slug": "/deployment",
    "description": "Current local orchestration, Kubernetes deployment model, ingress, and delivery pipeline for MIBO",
    "category": "deployment",
    "order": 60,
    "children": [
      {
        "title": "Docker & Images",
        "slug": "/deployment/docker",
        "description": "Dockerfiles, container builds, and image publishing across the MIBO platform",
        "category": "deployment",
        "order": 61
      },
      {
        "title": "Kubernetes Layout",
        "slug": "/deployment/kubernetes",
        "description": "How the repository splits backend Helm deployments, frontend manifests, and Traefik resources",
        "category": "deployment",
        "order": 62
      },
      {
        "title": "Helm Charts",
        "slug": "/deployment/helm",
        "description": "Current backend Helm charts and the values model used by deployment workflows",
        "category": "deployment",
        "order": 63
      },
      {
        "title": "Infrastructure",
        "slug": "/deployment/infrastructure",
        "description": "Current infrastructure dependencies across AppHost, Kubernetes resources, and environment configuration",
        "category": "deployment",
        "order": 64
      },
      {
        "title": "Ingress & TLS",
        "slug": "/deployment/ingress",
        "description": "Traefik ingress, public hostnames, and TLS behavior for the currently documented environment",
        "category": "deployment",
        "order": 65
      },
      {
        "title": "Observability",
        "slug": "/deployment/observability",
        "description": "Current operational visibility across status monitoring, logs, and deployment rollouts",
        "category": "deployment",
        "order": 66
      }
    ]
  },
  {
    "title": "Quality Overview",
    "slug": "/quality",
    "description": "Testing, CI/CD, security, and reliability practices for the current MIBO platform",
    "category": "quality",
    "order": 70,
    "children": [
      {
        "title": "Testing",
        "slug": "/quality/testing",
        "description": "Current automated test coverage and test execution entry points in the MIBO repository",
        "category": "quality",
        "order": 71
      },
      {
        "title": "CI/CD",
        "slug": "/quality/ci-cd",
        "description": "Current GitHub Actions delivery model for backend services, frontends, and docs",
        "category": "quality",
        "order": 72
      },
      {
        "title": "Security & Reliability",
        "slug": "/quality/security-and-reliability",
        "description": "Current auth, ownership, retry, and runtime reliability characteristics in MIBO",
        "category": "quality",
        "order": 73
      }
    ]
  }
];

export const searchIndex: Array<{
    title: string;
    description: string;
    slug: string;
    category: string;
}> = [
  {
    "title": "Platform Overview",
    "description": "Current product, platform, and repository overview for MIBO",
    "slug": "/getting-started",
    "category": "getting-started"
  },
  {
    "title": "Installation",
    "description": "Recommended ways to run the MIBO platform locally and what each mode starts",
    "slug": "/getting-started/installation",
    "category": "getting-started"
  },
  {
    "title": "Project Structure",
    "description": "Repository layout and how the codebase is partitioned by services, apps, infrastructure, and tests",
    "slug": "/getting-started/project-structure",
    "category": "getting-started"
  },
  {
    "title": "Platform Snapshot",
    "description": "Active platform summary for the current MIBO repository",
    "slug": "/getting-started/current-state",
    "category": "getting-started"
  },
  {
    "title": "Architecture Overview",
    "description": "Current runtime architecture for the MIBO platform",
    "slug": "/architecture",
    "category": "architecture"
  },
  {
    "title": "Services",
    "description": "Service catalog for the applications and shared runtime libraries in MIBO",
    "slug": "/architecture/services",
    "category": "architecture"
  },
  {
    "title": "Communication",
    "description": "Active request, streaming, identity propagation, and retry flows used by MIBO today",
    "slug": "/architecture/communication",
    "category": "architecture"
  },
  {
    "title": "Data Layer",
    "description": "Persistence ownership across PostgreSQL, MongoDB, Redis, and RabbitMQ",
    "slug": "/architecture/data-layer",
    "category": "architecture"
  },
  {
    "title": "Frontend Apps",
    "description": "The three frontend applications and the client-side generative UI runtime",
    "slug": "/architecture/frontend-apps",
    "category": "architecture"
  },
  {
    "title": "External Integrations",
    "description": "Runtime-facing third-party and adjacent external services used by the current MIBO platform",
    "slug": "/architecture/external-integrations",
    "category": "architecture"
  },
  {
    "title": "API Reference",
    "description": "Public HTTP contracts and action runtime contracts used by the current MIBO platform",
    "slug": "/api-reference",
    "category": "api-reference"
  },
  {
    "title": "API Gateway",
    "description": "Ocelot routes, authentication behavior, and claim propagation in MIBO.ApiGateway",
    "slug": "/api-reference/gateway",
    "category": "api-reference"
  },
  {
    "title": "Identity & Auth",
    "description": "Current IdentityService endpoints for login, registration, refresh, user info, finance connection state, and Spotify OAuth",
    "slug": "/api-reference/identity/auth",
    "category": "api-reference"
  },
  {
    "title": "Chat",
    "description": "Live chat endpoint exposed by ConversationService through the gateway",
    "slug": "/api-reference/conversation/chat",
    "category": "api-reference"
  },
  {
    "title": "Streaming",
    "description": "SSE event format between ConversationService, LangChainService, and the React client",
    "slug": "/api-reference/conversation/streaming",
    "category": "api-reference"
  },
  {
    "title": "Conversation Management",
    "description": "CRUD contracts for conversations and their stored message history",
    "slug": "/api-reference/conversation/actions",
    "category": "api-reference"
  },
  {
    "title": "Action Service Runtime",
    "description": "Public query and execute contracts plus the supported handler catalog in MIBO.ActionService",
    "slug": "/api-reference/action-service/runtime",
    "category": "api-reference"
  },
  {
    "title": "Integration Status",
    "description": "Monitoring summary contract exposed by ActionService and consumed by the status frontend",
    "slug": "/api-reference/action-service/status",
    "category": "api-reference"
  },
  {
    "title": "Finance Accounts",
    "description": "Finance account handlers exposed through Action Service",
    "slug": "/api-reference/finance/accounts",
    "category": "api-reference"
  },
  {
    "title": "Finance Transactions",
    "description": "Finance transaction list and search handlers exposed through Action Service",
    "slug": "/api-reference/finance/transactions",
    "category": "api-reference"
  },
  {
    "title": "Finance Expenses",
    "description": "Expense list and expense category handlers exposed through Action Service",
    "slug": "/api-reference/finance/expenses",
    "category": "api-reference"
  },
  {
    "title": "Finance Budgets",
    "description": "Budget handlers exposed through Action Service",
    "slug": "/api-reference/finance/budgets",
    "category": "api-reference"
  },
  {
    "title": "Finance Summary",
    "description": "Summary handlers used by the agent and generative UI",
    "slug": "/api-reference/finance/summary",
    "category": "api-reference"
  },
  {
    "title": "Finance Analytics",
    "description": "Expense and transaction analytics handlers exposed through Action Service",
    "slug": "/api-reference/finance/analytics",
    "category": "api-reference"
  },
  {
    "title": "Component Library",
    "description": "Documentation for the sandbox UI registry used by the client-side generative UI runtime",
    "slug": "/components",
    "category": "components"
  },
  {
    "title": "Chat & AI Overview",
    "description": "End-to-end architecture for MIBO's conversational runtime, AI agent pipeline, and structured UI responses",
    "slug": "/chat-system",
    "category": "chat-system"
  },
  {
    "title": "Conversation Flow",
    "description": "Detailed lifecycle from browser prompt to persisted assistant payload and client-side generative UI",
    "slug": "/chat-system/conversation-flow",
    "category": "chat-system"
  },
  {
    "title": "AI Agent Runtime",
    "description": "Detailed architecture of MIBO.LangChainService, including graph execution, prompts, tool orchestration, memory, and output shaping",
    "slug": "/chat-system/ai-agent-runtime",
    "category": "chat-system"
  },
  {
    "title": "Conversation Service Runtime",
    "description": "Detailed architecture of MIBO.ConversationService, including CRUD, SSE relay, Mongo persistence, ownership, and monitoring",
    "slug": "/chat-system/conversation-service-runtime",
    "category": "chat-system"
  },
  {
    "title": "Streaming & Live Runtime",
    "description": "SSE protocol, event semantics, and structured response handling across ConversationService, LangChainService, and the React client",
    "slug": "/chat-system/realtime",
    "category": "chat-system"
  },
  {
    "title": "Deployment",
    "description": "Current local orchestration, Kubernetes deployment model, ingress, and delivery pipeline for MIBO",
    "slug": "/deployment",
    "category": "deployment"
  },
  {
    "title": "Docker & Images",
    "description": "Dockerfiles, container builds, and image publishing across the MIBO platform",
    "slug": "/deployment/docker",
    "category": "deployment"
  },
  {
    "title": "Kubernetes Layout",
    "description": "How the repository splits backend Helm deployments, frontend manifests, and Traefik resources",
    "slug": "/deployment/kubernetes",
    "category": "deployment"
  },
  {
    "title": "Helm Charts",
    "description": "Current backend Helm charts and the values model used by deployment workflows",
    "slug": "/deployment/helm",
    "category": "deployment"
  },
  {
    "title": "Infrastructure",
    "description": "Current infrastructure dependencies across AppHost, Kubernetes resources, and environment configuration",
    "slug": "/deployment/infrastructure",
    "category": "deployment"
  },
  {
    "title": "Ingress & TLS",
    "description": "Traefik ingress, public hostnames, and TLS behavior for the currently documented environment",
    "slug": "/deployment/ingress",
    "category": "deployment"
  },
  {
    "title": "Observability",
    "description": "Current operational visibility across status monitoring, logs, and deployment rollouts",
    "slug": "/deployment/observability",
    "category": "deployment"
  },
  {
    "title": "Quality Overview",
    "description": "Testing, CI/CD, security, and reliability practices for the current MIBO platform",
    "slug": "/quality",
    "category": "quality"
  },
  {
    "title": "Sandbox Registry Components",
    "description": "Runtime component catalog for the generative UI registry used by the MIBO client",
    "slug": "/components/sandbox-registry",
    "category": "components"
  },
  {
    "title": "Testing",
    "description": "Current automated test coverage and test execution entry points in the MIBO repository",
    "slug": "/quality/testing",
    "category": "quality"
  },
  {
    "title": "ActionPanel",
    "description": "Action orchestration panel with payload templates and variant buttons",
    "slug": "/components/sandbox-registry/action-panel",
    "category": "components"
  },
  {
    "title": "CI/CD",
    "description": "Current GitHub Actions delivery model for backend services, frontends, and docs",
    "slug": "/quality/ci-cd",
    "category": "quality"
  },
  {
    "title": "BarChartCard",
    "description": "SVG bar chart with grouped, stacked and horizontal modes",
    "slug": "/components/sandbox-registry/bar-chart-card",
    "category": "components"
  },
  {
    "title": "Security & Reliability",
    "description": "Current auth, ownership, retry, and runtime reliability characteristics in MIBO",
    "slug": "/quality/security-and-reliability",
    "category": "quality"
  },
  {
    "title": "Carousel",
    "description": "Generic registry-based horizontal list renderer",
    "slug": "/components/sandbox-registry/carousel",
    "category": "components"
  },
  {
    "title": "CartSummaryCard",
    "description": "Checkout summary card with product rows and totals",
    "slug": "/components/sandbox-registry/cart-summary-card",
    "category": "components"
  },
  {
    "title": "CategoryChips",
    "description": "Interactive category selector for filtering flows",
    "slug": "/components/sandbox-registry/category-chips",
    "category": "components"
  },
  {
    "title": "EmailComposer",
    "description": "Gmail-oriented email draft composer with editable recipients, subject and body",
    "slug": "/components/sandbox-registry/email-composer",
    "category": "components"
  },
  {
    "title": "DataTableCard",
    "description": "Configurable table with search, sorting, and actions",
    "slug": "/components/sandbox-registry/data-table-card",
    "category": "components"
  },
  {
    "title": "FormCard",
    "description": "Schema-driven dynamic form with submit and reset actions",
    "slug": "/components/sandbox-registry/form-card",
    "category": "components"
  },
  {
    "title": "JsonViewerCard",
    "description": "JSON inspector with collapsible raw output",
    "slug": "/components/sandbox-registry/json-viewer-card",
    "category": "components"
  },
  {
    "title": "KpiCard",
    "description": "Single metric card for dashboard KPIs",
    "slug": "/components/sandbox-registry/kpi-card",
    "category": "components"
  },
  {
    "title": "LineChartCard",
    "description": "Interactive line chart with optional area and legend",
    "slug": "/components/sandbox-registry/line-chart-card",
    "category": "components"
  },
  {
    "title": "Markdown",
    "description": "Markdown renderer with GFM and code highlighting",
    "slug": "/components/sandbox-registry/markdown",
    "category": "components"
  },
  {
    "title": "PageTitle",
    "description": "Title and subtitle block with runtime binding",
    "slug": "/components/sandbox-registry/page-title",
    "category": "components"
  },
  {
    "title": "Pagination",
    "description": "Prev/next pager with computed page state",
    "slug": "/components/sandbox-registry/pagination",
    "category": "components"
  },
  {
    "title": "PieChartCard",
    "description": "Donut-style pie chart with legend and hover focus",
    "slug": "/components/sandbox-registry/pie-chart-card",
    "category": "components"
  },
  {
    "title": "ProductCarouselCard",
    "description": "Product rail with open and secondary actions",
    "slug": "/components/sandbox-registry/product-carousel-card",
    "category": "components"
  },
  {
    "title": "ProductDetailCard",
    "description": "Detailed product card with quantity and cart action",
    "slug": "/components/sandbox-registry/product-detail-card",
    "category": "components"
  },
  {
    "title": "SearchBar",
    "description": "Search input with Enter and button submit actions",
    "slug": "/components/sandbox-registry/search-bar",
    "category": "components"
  },
  {
    "title": "SortDropdown",
    "description": "Sort selector with customizable option payloads",
    "slug": "/components/sandbox-registry/sort-dropdown",
    "category": "components"
  },
  {
    "title": "SummaryPanel",
    "description": "Multi-KPI panel with trends and sparkline mini charts",
    "slug": "/components/sandbox-registry/summary-panel",
    "category": "components"
  },
  {
    "title": "TimelineCard",
    "description": "Event timeline list with clickable items",
    "slug": "/components/sandbox-registry/timeline-card",
    "category": "components"
  },
  {
    "title": "PomodoroTimer",
    "description": "Runtime Pomodoro timer component available in the client sandbox registry",
    "slug": "/components/sandbox-registry/pomodoro-timer",
    "category": "components"
  },
  {
    "title": "SpotifyPlayer",
    "description": "Runtime Spotify now-playing card available in the client sandbox registry",
    "slug": "/components/sandbox-registry/spotify-player",
    "category": "components"
  },
  {
    "title": "SpotifyTrackList",
    "description": "Runtime Spotify track-list component available in the client sandbox registry",
    "slug": "/components/sandbox-registry/spotify-track-list",
    "category": "components"
  }
];
